name: dnd_character_list
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  injectable: ^2.5.0
  get_it: ^8.0.2
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  collection: ^1.18.0
  gap: ^3.0.1
  fading_edge_scrollview: ^4.1.1
  shared_preferences: ^2.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inkulinati
      fonts:
        - asset: assets/fonts/Inkulinati-Regular.otf
