import 'package:dnd_character_list/domain/models/classes/class_kind.dart';

enum SpellSlot {
  conspiracy(0),
  level1(2),
  level2(3),
  level3(5),
  level4(6),
  level5(7),
  level6(9),
  level7(10),
  level8(11),
  level9(13);

  final int mana;

  const SpellSlot(this.mana);

  int compareTo(SpellSlot other) => index - other.index;

  String get name => switch (this) {
        SpellSlot.conspiracy => 'Заговор',
        SpellSlot.level1 => '1 уровень',
        SpellSlot.level2 => '2 уровень',
        SpellSlot.level3 => '3 уровень',
        SpellSlot.level4 => '4 уровень',
        SpellSlot.level5 => '5 уровень',
        SpellSlot.level6 => '6 уровень',
        SpellSlot.level7 => '7 уровень',
        SpellSlot.level8 => '8 уровень',
        SpellSlot.level9 => '9 уровень',
      };

  static Map<SpellSlot, int> getSpellCells(Map<ClassKind, int> classes) {
    final magicLevel = classes.entries.fold(
      0,
      (prev, e) => prev + (e.value * e.key.magicLevelMultiplier).toInt(),
    );
    if (magicLevel == 0) {
      return {};
    }
    return Map.fromEntries(spellSlotsTable[magicLevel]!.entries.where((element) => element.value > 0,));
  }
}

const spellSlotsTable = {
  1: {
    SpellSlot.level1: 2,
    SpellSlot.level2: 0,
    SpellSlot.level3: 0,
    SpellSlot.level4: 0,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  2: {
    SpellSlot.level1: 3,
    SpellSlot.level2: 0,
    SpellSlot.level3: 0,
    SpellSlot.level4: 0,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  3: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 2,
    SpellSlot.level3: 0,
    SpellSlot.level4: 0,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  4: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 0,
    SpellSlot.level4: 0,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  5: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 2,
    SpellSlot.level4: 0,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  6: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 0,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  7: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 1,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  8: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 2,
    SpellSlot.level5: 0,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  9: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 1,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  10: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 0,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  11: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  12: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 0,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  13: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 1,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  14: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 1,
    SpellSlot.level8: 0,
    SpellSlot.level9: 0,
  },
  15: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 1,
    SpellSlot.level8: 1,
    SpellSlot.level9: 0,
  },
  16: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 1,
    SpellSlot.level8: 1,
    SpellSlot.level9: 0,
  },
  17: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 2,
    SpellSlot.level6: 1,
    SpellSlot.level7: 1,
    SpellSlot.level8: 1,
    SpellSlot.level9: 1,
  },
  18: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 3,
    SpellSlot.level6: 1,
    SpellSlot.level7: 1,
    SpellSlot.level8: 1,
    SpellSlot.level9: 1,
  },
  19: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 3,
    SpellSlot.level6: 2,
    SpellSlot.level7: 1,
    SpellSlot.level8: 1,
    SpellSlot.level9: 1,
  },
  20: {
    SpellSlot.level1: 4,
    SpellSlot.level2: 3,
    SpellSlot.level3: 3,
    SpellSlot.level4: 3,
    SpellSlot.level5: 3,
    SpellSlot.level6: 2,
    SpellSlot.level7: 2,
    SpellSlot.level8: 1,
    SpellSlot.level9: 1,
  },
};
